#! /bin/bash
echo "Username"
read username
echo "Password"
read password
echo "Email"
read password
echo "Creating superuser in lms"
echo "$password
$password
" | tutor local run lms ./manage.py lms createsuperuser   --username $username --email $email
echo "Creating superuser in discovery"
echo "$password
$password
"
| tutor local run discovery ./manage.py createsuperuser --username $username --email $email
echo "Creating superuser in ecommerce"
echo "$password 
$password
"| tutor local run ecommerce ./manage.py createsuperuser --username $username --email $email
echo $username
